# docker 注册表服务器配置
version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
#  hooks:
#    - type: mail
#      disabled: true
#      levels:
#        - panic
#      options:
#        smtp:
#          addr: mail.example.com:25
#          username: mailuser
#          password: password
#          insecure: true
#        from: sender@example.com
#        to:
#          - errors@example.com
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: true
  redirect:
    disable: false
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  net: tcp
  secret: zhcppy
  relativeurls: false
#  debug:
#    addr: :5001
#    prometheus:
#      enabled: true
#      path: /metrics
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
notifications:
  endpoints:
    - name: manage
      disabled: true #禁用
      url: http://registry_manager:5002/envelope
      headers:
        Authorization: [ Bearer manage ]
      timeout: 15s
      threshold: 10
      backoff: 2s
      ignoredmediatypes:
        - application/octet-stream