# Author: zhcppy
# Time: 2019.08.09
# command:
#    - docker run -d --name registry -p 5000:5000 --restart=always registry:latest

version: "3.5"

services:
  registry:
    container_name: registry
    image: registry:latest
    restart: always
    ports:
      - "5000:5000"
    #    - "5001:5001"
    #  volumes:
    #    - ./registry/config.yml:/etc/docker/registry/config.yml
    #    - ./registry/data:/var/lib/registry
    environment:
      - MANAGER_PORT=5000
    extra_hosts:
      - "zhcppy:192.168.20.78"
    networks:
      - zhcppy_net

networks:
  zhcppy_net
    external: true
    driver: bridge


