# Author: zhcppy
# Time: 2019.09.16
# command:
#   - docker run -d -p 3306:3306 --name mysql --restart always -e MYSQL_ROOT_PASSWORD=12345678 mysql:latest
#   - docker exec -it mysql mysql -uroot -p
#   - ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '12345678';
#   - select user,host,authentication_string,plugin from mysql.user;
#   - update mysql.user set host='%' where user='root';
#   - flush privileges;
#   - delete from mysql.user where user='root' and host='localhost';
#   - docker exec mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /root/all-databases.sql
#   - docker exec -i mysql sh -c 'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD"' < /root/all-databases.sql

version: "3.5"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
