# Author: zhcppy
# Time: 2019.09.16
# doc:
#   - 集成测试工具（CI）https://github.com/drone/drone
#

version: "3.5"

services:
  drone:
    container_name: drone
    image: drone/drone:latest
    networks:
      - zhcppy_net
    ports:
      - 5008:5008
    environment:
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GOGS_SERVER=https://github.com
      - DRONE_GOGS_SKIP_VERIFY=true
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=localhost
      - DRONE_SERVER_PORT=:5008
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    restart: always
#    deploy:
#      mode: replicated
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#        delay: 500ms
#        max_attempts: 3

networks:
  zhcppy_net:
    external: true
    driver: bridge
