# Author: zhcppy
# Time: 2019.09.16
# command:
#   - docker logs mysql 2>&1 | grep GENERATED
#   - docker exec -it mysql mysql -uroot -p
#   - ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root1234'
#   - select user,host,authentication_string,plugin from mysql.user;
#   - update mysql.user set host='%' where user='root';
#   - flush privileges;

version: "3.5"

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    restart: always
    networks:
      - zhcppy_net

networks:
  zhcppy_net:
    external: true
    driver: bridge

